# Generated by Django 4.0.4 on 2022-05-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(blank=True, default='post_images/blankpicture.jpg', null=True, upload_to='profile_images'),
        ),
    ]
